/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package manning.devices.canonical.m2;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CanonicalMetadata extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5678917983147860250L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CanonicalMetadata\",\"namespace\":\"manning.devices.canonical.m2\",\"fields\":[{\"name\":\"uuid\",\"type\":\"string\"},{\"name\":\"arrival_time_ms\",\"type\":[\"long\"]},{\"name\":\"start_time_ms\",\"type\":[\"long\"]},{\"name\":\"end_time_ms\",\"type\":[\"long\"]},{\"name\":\"withError\",\"type\":[\"null\",\"boolean\"]},{\"name\":\"slow\",\"type\":[\"null\",\"boolean\"]},{\"name\":\"number_events\",\"type\":[\"null\",\"int\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence uuid;
  @Deprecated public java.lang.Object arrival_time_ms;
  @Deprecated public java.lang.Object start_time_ms;
  @Deprecated public java.lang.Object end_time_ms;
  @Deprecated public java.lang.Boolean withError;
  @Deprecated public java.lang.Boolean slow;
  @Deprecated public java.lang.Integer number_events;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CanonicalMetadata() {}

  /**
   * All-args constructor.
   */
  public CanonicalMetadata(java.lang.CharSequence uuid, java.lang.Object arrival_time_ms, java.lang.Object start_time_ms, java.lang.Object end_time_ms, java.lang.Boolean withError, java.lang.Boolean slow, java.lang.Integer number_events) {
    this.uuid = uuid;
    this.arrival_time_ms = arrival_time_ms;
    this.start_time_ms = start_time_ms;
    this.end_time_ms = end_time_ms;
    this.withError = withError;
    this.slow = slow;
    this.number_events = number_events;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uuid;
    case 1: return arrival_time_ms;
    case 2: return start_time_ms;
    case 3: return end_time_ms;
    case 4: return withError;
    case 5: return slow;
    case 6: return number_events;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uuid = (java.lang.CharSequence)value$; break;
    case 1: arrival_time_ms = (java.lang.Object)value$; break;
    case 2: start_time_ms = (java.lang.Object)value$; break;
    case 3: end_time_ms = (java.lang.Object)value$; break;
    case 4: withError = (java.lang.Boolean)value$; break;
    case 5: slow = (java.lang.Boolean)value$; break;
    case 6: number_events = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'uuid' field.
   */
  public java.lang.CharSequence getUuid() {
    return uuid;
  }

  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.CharSequence value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'arrival_time_ms' field.
   */
  public java.lang.Object getArrivalTimeMs() {
    return arrival_time_ms;
  }

  /**
   * Sets the value of the 'arrival_time_ms' field.
   * @param value the value to set.
   */
  public void setArrivalTimeMs(java.lang.Object value) {
    this.arrival_time_ms = value;
  }

  /**
   * Gets the value of the 'start_time_ms' field.
   */
  public java.lang.Object getStartTimeMs() {
    return start_time_ms;
  }

  /**
   * Sets the value of the 'start_time_ms' field.
   * @param value the value to set.
   */
  public void setStartTimeMs(java.lang.Object value) {
    this.start_time_ms = value;
  }

  /**
   * Gets the value of the 'end_time_ms' field.
   */
  public java.lang.Object getEndTimeMs() {
    return end_time_ms;
  }

  /**
   * Sets the value of the 'end_time_ms' field.
   * @param value the value to set.
   */
  public void setEndTimeMs(java.lang.Object value) {
    this.end_time_ms = value;
  }

  /**
   * Gets the value of the 'withError' field.
   */
  public java.lang.Boolean getWithError() {
    return withError;
  }

  /**
   * Sets the value of the 'withError' field.
   * @param value the value to set.
   */
  public void setWithError(java.lang.Boolean value) {
    this.withError = value;
  }

  /**
   * Gets the value of the 'slow' field.
   */
  public java.lang.Boolean getSlow() {
    return slow;
  }

  /**
   * Sets the value of the 'slow' field.
   * @param value the value to set.
   */
  public void setSlow(java.lang.Boolean value) {
    this.slow = value;
  }

  /**
   * Gets the value of the 'number_events' field.
   */
  public java.lang.Integer getNumberEvents() {
    return number_events;
  }

  /**
   * Sets the value of the 'number_events' field.
   * @param value the value to set.
   */
  public void setNumberEvents(java.lang.Integer value) {
    this.number_events = value;
  }

  /**
   * Creates a new CanonicalMetadata RecordBuilder.
   * @return A new CanonicalMetadata RecordBuilder
   */
  public static manning.devices.canonical.m2.CanonicalMetadata.Builder newBuilder() {
    return new manning.devices.canonical.m2.CanonicalMetadata.Builder();
  }
  
  /**
   * Creates a new CanonicalMetadata RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CanonicalMetadata RecordBuilder
   */
  public static manning.devices.canonical.m2.CanonicalMetadata.Builder newBuilder(manning.devices.canonical.m2.CanonicalMetadata.Builder other) {
    return new manning.devices.canonical.m2.CanonicalMetadata.Builder(other);
  }
  
  /**
   * Creates a new CanonicalMetadata RecordBuilder by copying an existing CanonicalMetadata instance.
   * @param other The existing instance to copy.
   * @return A new CanonicalMetadata RecordBuilder
   */
  public static manning.devices.canonical.m2.CanonicalMetadata.Builder newBuilder(manning.devices.canonical.m2.CanonicalMetadata other) {
    return new manning.devices.canonical.m2.CanonicalMetadata.Builder(other);
  }
  
  /**
   * RecordBuilder for CanonicalMetadata instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CanonicalMetadata>
    implements org.apache.avro.data.RecordBuilder<CanonicalMetadata> {

    private java.lang.CharSequence uuid;
    private java.lang.Object arrival_time_ms;
    private java.lang.Object start_time_ms;
    private java.lang.Object end_time_ms;
    private java.lang.Boolean withError;
    private java.lang.Boolean slow;
    private java.lang.Integer number_events;

    /** Creates a new Builder */
    private Builder() {
      super(manning.devices.canonical.m2.CanonicalMetadata.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(manning.devices.canonical.m2.CanonicalMetadata.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uuid)) {
        this.uuid = data().deepCopy(fields()[0].schema(), other.uuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.arrival_time_ms)) {
        this.arrival_time_ms = data().deepCopy(fields()[1].schema(), other.arrival_time_ms);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.start_time_ms)) {
        this.start_time_ms = data().deepCopy(fields()[2].schema(), other.start_time_ms);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.end_time_ms)) {
        this.end_time_ms = data().deepCopy(fields()[3].schema(), other.end_time_ms);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.withError)) {
        this.withError = data().deepCopy(fields()[4].schema(), other.withError);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.slow)) {
        this.slow = data().deepCopy(fields()[5].schema(), other.slow);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.number_events)) {
        this.number_events = data().deepCopy(fields()[6].schema(), other.number_events);
        fieldSetFlags()[6] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing CanonicalMetadata instance
     * @param other The existing instance to copy.
     */
    private Builder(manning.devices.canonical.m2.CanonicalMetadata other) {
            super(manning.devices.canonical.m2.CanonicalMetadata.SCHEMA$);
      if (isValidValue(fields()[0], other.uuid)) {
        this.uuid = data().deepCopy(fields()[0].schema(), other.uuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.arrival_time_ms)) {
        this.arrival_time_ms = data().deepCopy(fields()[1].schema(), other.arrival_time_ms);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.start_time_ms)) {
        this.start_time_ms = data().deepCopy(fields()[2].schema(), other.start_time_ms);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.end_time_ms)) {
        this.end_time_ms = data().deepCopy(fields()[3].schema(), other.end_time_ms);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.withError)) {
        this.withError = data().deepCopy(fields()[4].schema(), other.withError);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.slow)) {
        this.slow = data().deepCopy(fields()[5].schema(), other.slow);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.number_events)) {
        this.number_events = data().deepCopy(fields()[6].schema(), other.number_events);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'uuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getUuid() {
      return uuid;
    }

    /**
      * Sets the value of the 'uuid' field.
      * @param value The value of 'uuid'.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder setUuid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.uuid = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'uuid' field has been set.
      * @return True if the 'uuid' field has been set, false otherwise.
      */
    public boolean hasUuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'uuid' field.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'arrival_time_ms' field.
      * @return The value.
      */
    public java.lang.Object getArrivalTimeMs() {
      return arrival_time_ms;
    }

    /**
      * Sets the value of the 'arrival_time_ms' field.
      * @param value The value of 'arrival_time_ms'.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder setArrivalTimeMs(java.lang.Object value) {
      validate(fields()[1], value);
      this.arrival_time_ms = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'arrival_time_ms' field has been set.
      * @return True if the 'arrival_time_ms' field has been set, false otherwise.
      */
    public boolean hasArrivalTimeMs() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'arrival_time_ms' field.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder clearArrivalTimeMs() {
      arrival_time_ms = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'start_time_ms' field.
      * @return The value.
      */
    public java.lang.Object getStartTimeMs() {
      return start_time_ms;
    }

    /**
      * Sets the value of the 'start_time_ms' field.
      * @param value The value of 'start_time_ms'.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder setStartTimeMs(java.lang.Object value) {
      validate(fields()[2], value);
      this.start_time_ms = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'start_time_ms' field has been set.
      * @return True if the 'start_time_ms' field has been set, false otherwise.
      */
    public boolean hasStartTimeMs() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'start_time_ms' field.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder clearStartTimeMs() {
      start_time_ms = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'end_time_ms' field.
      * @return The value.
      */
    public java.lang.Object getEndTimeMs() {
      return end_time_ms;
    }

    /**
      * Sets the value of the 'end_time_ms' field.
      * @param value The value of 'end_time_ms'.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder setEndTimeMs(java.lang.Object value) {
      validate(fields()[3], value);
      this.end_time_ms = value;
      fieldSetFlags()[3] = true;
      return this; 
    }

    /**
      * Checks whether the 'end_time_ms' field has been set.
      * @return True if the 'end_time_ms' field has been set, false otherwise.
      */
    public boolean hasEndTimeMs() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'end_time_ms' field.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder clearEndTimeMs() {
      end_time_ms = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'withError' field.
      * @return The value.
      */
    public java.lang.Boolean getWithError() {
      return withError;
    }

    /**
      * Sets the value of the 'withError' field.
      * @param value The value of 'withError'.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder setWithError(java.lang.Boolean value) {
      validate(fields()[4], value);
      this.withError = value;
      fieldSetFlags()[4] = true;
      return this; 
    }

    /**
      * Checks whether the 'withError' field has been set.
      * @return True if the 'withError' field has been set, false otherwise.
      */
    public boolean hasWithError() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'withError' field.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder clearWithError() {
      withError = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'slow' field.
      * @return The value.
      */
    public java.lang.Boolean getSlow() {
      return slow;
    }

    /**
      * Sets the value of the 'slow' field.
      * @param value The value of 'slow'.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder setSlow(java.lang.Boolean value) {
      validate(fields()[5], value);
      this.slow = value;
      fieldSetFlags()[5] = true;
      return this; 
    }

    /**
      * Checks whether the 'slow' field has been set.
      * @return True if the 'slow' field has been set, false otherwise.
      */
    public boolean hasSlow() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'slow' field.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder clearSlow() {
      slow = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'number_events' field.
      * @return The value.
      */
    public java.lang.Integer getNumberEvents() {
      return number_events;
    }

    /**
      * Sets the value of the 'number_events' field.
      * @param value The value of 'number_events'.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder setNumberEvents(java.lang.Integer value) {
      validate(fields()[6], value);
      this.number_events = value;
      fieldSetFlags()[6] = true;
      return this; 
    }

    /**
      * Checks whether the 'number_events' field has been set.
      * @return True if the 'number_events' field has been set, false otherwise.
      */
    public boolean hasNumberEvents() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'number_events' field.
      * @return This builder.
      */
    public manning.devices.canonical.m2.CanonicalMetadata.Builder clearNumberEvents() {
      number_events = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public CanonicalMetadata build() {
      try {
        CanonicalMetadata record = new CanonicalMetadata();
        record.uuid = fieldSetFlags()[0] ? this.uuid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.arrival_time_ms = fieldSetFlags()[1] ? this.arrival_time_ms : (java.lang.Object) defaultValue(fields()[1]);
        record.start_time_ms = fieldSetFlags()[2] ? this.start_time_ms : (java.lang.Object) defaultValue(fields()[2]);
        record.end_time_ms = fieldSetFlags()[3] ? this.end_time_ms : (java.lang.Object) defaultValue(fields()[3]);
        record.withError = fieldSetFlags()[4] ? this.withError : (java.lang.Boolean) defaultValue(fields()[4]);
        record.slow = fieldSetFlags()[5] ? this.slow : (java.lang.Boolean) defaultValue(fields()[5]);
        record.number_events = fieldSetFlags()[6] ? this.number_events : (java.lang.Integer) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
